import type {
  Team,
  Player,
  Match,
  MatchTeamState,
  PlayerMatchStat,
  GameEvent,
  StandingsRow,
  TopScorer,
  TournamentEdition,
} from "./nbl-types";

// ─── Teams ────────────────────────────────────────────────────────────────────

export const TEAMS: Record<string, Team> = {
  heat: {
    id: "heat",
    name: "ABIDJAN HEAT",
    shortName: "HEAT",
    code: "AH",
    city: "Abidjan",
    primaryColor: "#D96813",
  },
  treichville: {
    id: "treichville",
    name: "TREICHVILLE",
    shortName: "TREICH.",
    code: "TR",
    city: "Treichville",
    primaryColor: "#2563EB",
  },
  blktop: {
    id: "blktop",
    name: "BLKTOP",
    shortName: "BLKTOP",
    code: "BT",
    city: "Abidjan",
    primaryColor: "#16A34A",
  },
  concrete: {
    id: "concrete",
    name: "CONCRETE",
    shortName: "CONCR.",
    code: "CN",
    city: "Dakar",
    primaryColor: "#9333EA",
  },
  vipers: {
    id: "vipers",
    name: "VIPERS",
    shortName: "VIPERS",
    code: "VP",
    city: "Cocody",
    primaryColor: "#DC2626",
  },
  hoopkings: {
    id: "hoopkings",
    name: "HOOP KINGS",
    shortName: "H.KINGS",
    code: "HK",
    city: "Plateau",
    primaryColor: "#D97706",
  },
  dunksquad: {
    id: "dunksquad",
    name: "DUNK SQUAD",
    shortName: "D.SQUAD",
    code: "DS",
    city: "Yopougon",
    primaryColor: "#0891B2",
  },
  rimrockers: {
    id: "rimrockers",
    name: "RIM ROCKERS",
    shortName: "RIM R.",
    code: "RR",
    city: "Marcory",
    primaryColor: "#7C3AED",
  },
};

// ─── Players ──────────────────────────────────────────────────────────────────

const makePlayer = (
  id: string,
  firstName: string,
  lastName: string,
  number: number,
  position: Player["position"],
  teamId: string,
  careerPpg: number,
  careerMatches: number,
): Player => ({
  id,
  firstName,
  lastName,
  number,
  position,
  teamId,
  careerPoints: Math.round(careerPpg * careerMatches),
  careerMatches,
  careerPpg,
  editionStats: {
    "2026": {
      editionId: "2026",
      editionName: "Summer League 2026",
      matches: Math.ceil(careerMatches / 2),
      totalPoints: Math.round(careerPpg * Math.ceil(careerMatches / 2)),
      ppg: careerPpg,
      fouls: Math.floor(Math.random() * 12) + 3,
    },
    "2023": {
      editionId: "2023",
      editionName: "Summer League 2023",
      matches: Math.floor(careerMatches / 2),
      totalPoints: Math.round(
        (careerPpg - 2.5) * Math.floor(careerMatches / 2),
      ),
      ppg: careerPpg - 2.5,
      fouls: Math.floor(Math.random() * 10) + 2,
    },
  },
});

export const PLAYERS: Record<string, Player> = {
  "malik-diop": makePlayer(
    "malik-diop",
    "Malik",
    "Diop",
    5,
    "SG",
    "heat",
    28.4,
    18,
  ),
  "kofi-asante": makePlayer(
    "kofi-asante",
    "Kofi",
    "Asante",
    11,
    "PG",
    "heat",
    19.2,
    18,
  ),
  "amara-bamba": makePlayer(
    "amara-bamba",
    "Amara",
    "Bamba",
    23,
    "SF",
    "heat",
    15.8,
    18,
  ),
  "ibrahim-coulibaly": makePlayer(
    "ibrahim-coulibaly",
    "Ibrahim",
    "Coulibaly",
    33,
    "PF",
    "heat",
    12.1,
    18,
  ),
  "sekou-traore": makePlayer(
    "sekou-traore",
    "Sekou",
    "Traoré",
    4,
    "C",
    "heat",
    9.4,
    18,
  ),
  "dimitri-kouassi": makePlayer(
    "dimitri-kouassi",
    "Dimitri",
    "Kouassi",
    7,
    "PG",
    "treichville",
    22.7,
    16,
  ),
  "yves-boti": makePlayer(
    "yves-boti",
    "Yves",
    "Boti",
    14,
    "SG",
    "treichville",
    17.3,
    16,
  ),
  "eric-gnagne": makePlayer(
    "eric-gnagne",
    "Eric",
    "Gnagné",
    21,
    "SF",
    "treichville",
    14.5,
    16,
  ),
  "roger-dago": makePlayer(
    "roger-dago",
    "Roger",
    "Dago",
    42,
    "PF",
    "treichville",
    11.2,
    16,
  ),
  "jean-koffi": makePlayer(
    "jean-koffi",
    "Jean",
    "Koffi",
    8,
    "C",
    "treichville",
    8.9,
    16,
  ),
  "thierry-kouame": makePlayer(
    "thierry-kouame",
    "Thierry",
    "Kouamé",
    3,
    "SG",
    "blktop",
    24.1,
    14,
  ),
  "luc-yao": makePlayer("luc-yao", "Luc", "Yao", 10, "PG", "blktop", 18.6, 14),
};

// ─── Player match stats helpers ───────────────────────────────────────────────

const pms = (
  playerId: string,
  pts: number,
  fouls: number,
  isOnCourt: boolean,
): PlayerMatchStat => ({
  player: PLAYERS[playerId],
  points: pts,
  fouls,
  assists: 0,
  rebounds: 0,
  isOnCourt,
});

// ─── Matches ──────────────────────────────────────────────────────────────────

const heatState: MatchTeamState = {
  team: TEAMS.heat,
  score: 86,
  fouls: 3,
  timeoutsLeft: 1,
  onCourt: [
    pms("malik-diop", 24, 2, true),
    pms("kofi-asante", 18, 1, true),
    pms("amara-bamba", 14, 3, true),
    pms("ibrahim-coulibaly", 16, 2, true),
    pms("sekou-traore", 14, 0, true),
  ],
  bench: [],
};

const treichvilleState: MatchTeamState = {
  team: TEAMS.treichville,
  score: 82,
  fouls: 2,
  timeoutsLeft: 2,
  onCourt: [
    pms("dimitri-kouassi", 25, 3, true),
    pms("yves-boti", 19, 1, true),
    pms("eric-gnagne", 16, 2, true),
    pms("roger-dago", 12, 1, true),
    pms("jean-koffi", 10, 0, true),
  ],
  bench: [],
};

export const MATCHES: Record<string, Match> = {
  "match-1": {
    id: "match-1",
    status: "live",
    quarter: "Q4",
    clockSeconds: 261,
    homeState: heatState,
    awayState: treichvilleState,
    possession: "home",
    venue: "Stade Municipal, Abidjan",
    scheduledAt: "2026-03-17T19:00:00Z",
    tags: ["FINALS"],
    events: [
      {
        id: "e1",
        matchId: "match-1",
        quarter: "Q1",
        clockSeconds: 580,
        type: "pts2",
        value: 2,
        team: "home",
        playerId: "malik-diop",
        playerName: "M. Diop",
        homeScore: 2,
        awayScore: 0,
        createdAt: "",
      },
      {
        id: "e2",
        matchId: "match-1",
        quarter: "Q1",
        clockSeconds: 540,
        type: "pts3",
        value: 3,
        team: "away",
        playerId: "dimitri-kouassi",
        playerName: "D. Kouassi",
        homeScore: 2,
        awayScore: 3,
        createdAt: "",
      },
      {
        id: "e3",
        matchId: "match-1",
        quarter: "Q2",
        clockSeconds: 460,
        type: "pts2",
        value: 2,
        team: "home",
        playerId: "kofi-asante",
        playerName: "K. Asante",
        homeScore: 24,
        awayScore: 19,
        createdAt: "",
      },
      {
        id: "e4",
        matchId: "match-1",
        quarter: "Q2",
        clockSeconds: 390,
        type: "foul",
        value: 0,
        team: "away",
        playerId: "yves-boti",
        playerName: "Y. Boti",
        homeScore: 24,
        awayScore: 19,
        createdAt: "",
      },
      {
        id: "e5",
        matchId: "match-1",
        quarter: "Q3",
        clockSeconds: 520,
        type: "pts3",
        value: 3,
        team: "home",
        playerId: "malik-diop",
        playerName: "M. Diop",
        homeScore: 52,
        awayScore: 48,
        createdAt: "",
      },
      {
        id: "e6",
        matchId: "match-1",
        quarter: "Q3",
        clockSeconds: 200,
        type: "pts2",
        value: 2,
        team: "away",
        playerId: "dimitri-kouassi",
        playerName: "D. Kouassi",
        homeScore: 68,
        awayScore: 65,
        createdAt: "",
      },
      {
        id: "e7",
        matchId: "match-1",
        quarter: "Q4",
        clockSeconds: 480,
        type: "pts2",
        value: 2,
        team: "home",
        playerId: "amara-bamba",
        playerName: "A. Bamba",
        homeScore: 78,
        awayScore: 72,
        createdAt: "",
      },
      {
        id: "e8",
        matchId: "match-1",
        quarter: "Q4",
        clockSeconds: 350,
        type: "foul",
        value: 0,
        team: "home",
        playerId: "ibrahim-coulibaly",
        playerName: "I. Coulibaly",
        homeScore: 78,
        awayScore: 72,
        createdAt: "",
      },
      {
        id: "e9",
        matchId: "match-1",
        quarter: "Q4",
        clockSeconds: 261,
        type: "pts3",
        value: 3,
        team: "home",
        playerId: "malik-diop",
        playerName: "M. Diop",
        homeScore: 86,
        awayScore: 82,
        createdAt: "",
      },
    ] as GameEvent[],
  },
  "match-2": {
    id: "match-2",
    status: "upcoming",
    quarter: "Q1",
    clockSeconds: 600,
    homeState: {
      team: TEAMS.vipers,
      score: 0,
      fouls: 0,
      timeoutsLeft: 3,
      onCourt: [],
      bench: [],
    },
    awayState: {
      team: TEAMS.hoopkings,
      score: 0,
      fouls: 0,
      timeoutsLeft: 3,
      onCourt: [],
      bench: [],
    },
    possession: "home",
    venue: "Stade Municipal, Abidjan",
    scheduledAt: "2026-03-18T19:30:00Z",
    tags: [],
    events: [],
  },
  "match-3": {
    id: "match-3",
    status: "live",
    quarter: "Q2",
    clockSeconds: 480,
    homeState: {
      team: TEAMS.dunksquad,
      score: 45,
      fouls: 1,
      timeoutsLeft: 2,
      onCourt: [],
      bench: [],
    },
    awayState: {
      team: TEAMS.rimrockers,
      score: 30,
      fouls: 2,
      timeoutsLeft: 1,
      onCourt: [],
      bench: [],
    },
    possession: "home",
    venue: "Treichville Arena",
    scheduledAt: "2026-03-17T21:00:00Z",
    tags: [],
    ticketPrice: "1 500 FCFA",
    events: [],
  },
};

export const MATCHES_LIST = Object.values(MATCHES);

// ─── Standings ────────────────────────────────────────────────────────────────

export const STANDINGS: StandingsRow[] = [
  {
    rank: 1,
    team: TEAMS.heat,
    played: 8,
    won: 7,
    lost: 1,
    pointsFor: 612,
    pointsAgainst: 548,
    diff: 64,
    pts: 14,
  },
  {
    rank: 2,
    team: TEAMS.blktop,
    played: 8,
    won: 6,
    lost: 2,
    pointsFor: 594,
    pointsAgainst: 551,
    diff: 43,
    pts: 12,
  },
  {
    rank: 3,
    team: TEAMS.treichville,
    played: 8,
    won: 5,
    lost: 3,
    pointsFor: 571,
    pointsAgainst: 558,
    diff: 13,
    pts: 10,
  },
  {
    rank: 4,
    team: TEAMS.concrete,
    played: 8,
    won: 5,
    lost: 3,
    pointsFor: 563,
    pointsAgainst: 554,
    diff: 9,
    pts: 10,
  },
  {
    rank: 5,
    team: TEAMS.vipers,
    played: 8,
    won: 4,
    lost: 4,
    pointsFor: 538,
    pointsAgainst: 540,
    diff: -2,
    pts: 8,
  },
  {
    rank: 6,
    team: TEAMS.dunksquad,
    played: 8,
    won: 3,
    lost: 5,
    pointsFor: 521,
    pointsAgainst: 555,
    diff: -34,
    pts: 6,
  },
  {
    rank: 7,
    team: TEAMS.hoopkings,
    played: 8,
    won: 2,
    lost: 6,
    pointsFor: 498,
    pointsAgainst: 572,
    diff: -74,
    pts: 4,
  },
  {
    rank: 8,
    team: TEAMS.rimrockers,
    played: 8,
    won: 0,
    lost: 8,
    pointsFor: 451,
    pointsAgainst: 612,
    diff: -161,
    pts: 0,
  },
];

// ─── Top Scorers ──────────────────────────────────────────────────────────────

export const TOP_SCORERS: TopScorer[] = [
  {
    rank: 1,
    player: PLAYERS["malik-diop"],
    team: TEAMS.heat,
    matches: 8,
    totalPoints: 227,
    ppg: 28.4,
  },
  {
    rank: 2,
    player: PLAYERS["thierry-kouame"],
    team: TEAMS.blktop,
    matches: 8,
    totalPoints: 193,
    ppg: 24.1,
  },
  {
    rank: 3,
    player: PLAYERS["dimitri-kouassi"],
    team: TEAMS.treichville,
    matches: 7,
    totalPoints: 159,
    ppg: 22.7,
  },
  {
    rank: 4,
    player: PLAYERS["kofi-asante"],
    team: TEAMS.heat,
    matches: 8,
    totalPoints: 154,
    ppg: 19.2,
  },
  {
    rank: 5,
    player: PLAYERS["luc-yao"],
    team: TEAMS.blktop,
    matches: 8,
    totalPoints: 149,
    ppg: 18.6,
  },
  {
    rank: 6,
    player: PLAYERS["yves-boti"],
    team: TEAMS.treichville,
    matches: 7,
    totalPoints: 121,
    ppg: 17.3,
  },
  {
    rank: 7,
    player: PLAYERS["amara-bamba"],
    team: TEAMS.heat,
    matches: 8,
    totalPoints: 126,
    ppg: 15.8,
  },
  {
    rank: 8,
    player: PLAYERS["eric-gnagne"],
    team: TEAMS.treichville,
    matches: 7,
    totalPoints: 102,
    ppg: 14.5,
  },
];

// ─── Edition ──────────────────────────────────────────────────────────────────

export const CURRENT_EDITION: TournamentEdition = {
  id: "2026",
  name: "Summer League 2026",
  year: 2026,
  isActive: true,
  teams: Object.values(TEAMS),
};
